version: '2'

services:
    peer1.org2.oslab.com:
        container_name: peer1.org2.oslab.com
        image: hyperledger/fabric-peer:1.4.1
        environment:
        - FABRIC_LOGGING_SPEC=grpc=debug:debug
        - CORE_CHAINCODE_LOGGING_LEVEL=INFO
        - CORE_CHAINCODE_LOGGING_SHIM=INFO
        - CORE_CHAINCODE_EXECUTETIMEOUT=999999
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_PEER_ID=peer1.org2.oslab.com
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_LOCALMSPID=Org2MSP
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
        - CORE_PEER_ADDRESS=peer1.org2.oslab.com:7051
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.oslab.com:7051
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK_MODE_NAME}
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: peer node start
        ports:
        - 7051:7051
        volumes:
        - /var/run/:/host/var/run/
        - ../../config/config-kafka_325_batch_100/crypto-config/peerOrganizations/org2.oslab.com/peers/peer1.org2.oslab.com/:/etc/hyperledger/msp/peer
        extra_hosts:
        - "orderer0.oslab.com:10.0.0.236"
        - "orderer1.oslab.com:10.0.0.237"
        - "orderer2.oslab.com:10.0.0.238"
        