version: '2'

services:
    peer0.org2.oslab.com:
        container_name: peer0.org2.oslab.com
        network_mode: host
        image: hyperledger/fabric-peer:1.4.1
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_SHIM=ERROR
        - CORE_CHAINCODE_EXECUTETIMEOUT=999999
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_PEER_ID=peer0.org2.oslab.com
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_LOCALMSPID=Org2MSP
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
        - CORE_PEER_ADDRESS=10.0.0.241:7051
        - CORE_PEER_CHAINCODELISTENADDRESS=10.0.0.241:7052
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.0.0.241:7051
        # - CORE_PEER_ADDRESS=peer0.org1.oslab.com:7051
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        # - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.oslab.com:7051
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
        # - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=kafka100_default
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: peer node start
        ports:
        - 7051:7051
        - 7052:7052
        - 2375:2375
        - 2376:2376        
        volumes:
        - /var/run/:/host/var/run/
        - ../../config/config-kafka100/crypto-config/peerOrganizations/org2.oslab.com/peers/peer0.org2.oslab.com/:/etc/hyperledger/msp/peer

        extra_hosts:
        - orderer0.oslab.com:10.0.0.236
        - orderer1.oslab.com:10.0.0.237
        - orderer2.oslab.com:10.0.0.238
        